language : generic
sudo: required
services: 
    - docker

before_install:
    - docker build -t my_test -f Dockerfile.dev .

script:
    - docker run -e CI=true my_test npm run test

deploy:
    provider : elasticbeanstalk
    region : "ap-southeast-2"
    app : "docker-react"
    env : "DockerReact-env"
    bucket_name : "elasticbeanstalk-ap-southeast-2-808566145736"
    bucket_path : "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY